// src/App.tsx
import { Toaster } from "@/components/base/sonner";
import { useCryptoKeys } from "@/hooks/useCryptoKeys";
import { Header } from "@/components/ui/header";
import { Algorithmns } from "@/components/ui/algorithms";
import { KeyControlCard } from "./components/ui/keys/card";
import { useStreamSupport } from "./hooks/useStreamSupport";
import { AlertStreamNotSupported } from "./components/ui/static";
import { EncryptFileCard } from "@/components/ui/file/encrypt";
import { useFileDecrypt, useFileEncrypt } from "./hooks/useFileCryptoStream";
import { DecryptFileCard } from "./components/ui/file/decrypt";

const MAX_FILE_SIZE = 1.5 * 1024 * 1024 * 1024;
const WARNING_FILE_SIZE = 500 * 1024 * 1024;

function App() {
  const keys = useCryptoKeys();

  const streamSupported = useStreamSupport();
  const option = {
    streamSupported: streamSupported,
    maxFileSize: MAX_FILE_SIZE,
    warnFileSize: WARNING_FILE_SIZE,
  };
  const enc = useFileEncrypt(option);
  const dec = useFileDecrypt(option);

  return (
    <main className="min-h-dvh bg-background text-foreground">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-4 py-5 sm:px-6 lg:px-8">
        <Header privateKey={keys.privateKey} publicKey={keys.publicKey} />
        {streamSupported ? null : <AlertStreamNotSupported />}
        <section className="grid gap-6 lg:grid-cols-[0.3fr_0.9fr]">
          <KeyControlCard keys={keys} />

          <div className="grid gap-6">
            <EncryptFileCard files={enc} keys={keys} />
            <DecryptFileCard files={dec} keys={keys} />

            <Algorithmns />
          </div>
        </section>
      </div>
      <Toaster position="bottom-right" />
    </main>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import AlertStreamNotSupported from "./components/ui/static/AlertStreamNotSupported.vue";
import { useCryptoKeys } from "@/composables/useCryptoKeys.ts";
import { useStreamSupport } from "@/composables/useStreamSupport.ts";
import {
  useFileEncrypt,
  useFileDecrypt,
} from "@/composables/useFileCryptoStream.ts";
import { useShareLink } from "./composables/useShareLink.ts";
import EncryptFileCard from "./components/ui/file/EncryptFileCard.vue";
import DecryptFileCard from "./components/ui/file/DecryptFileCard.vue";
import Header from "./components/ui/header/Header.vue";
import Algorithmns from "./components/ui/algorithms/Algorithmns.vue";
import { Toaster } from "@/components/base/sonner";
import KeyControlCard from "./components/ui/keys/card/KeyControlCard.vue";
const MAX_FILE_SIZE = 1.5 * 1024 * 1024 * 1024;
const WARNING_FILE_SIZE = 500 * 1024 * 1024;

const keys = useCryptoKeys();

const streamSupported = useStreamSupport();
const option = {
  streamSupport: streamSupported,
  maxFileSize: MAX_FILE_SIZE,
  warnFileSize: WARNING_FILE_SIZE,
};
const enc = useFileEncrypt(option);
const dec = useFileDecrypt(option);
const { loadLink } = useShareLink();
onload = async () => {
  const publicJwk = loadLink();
  if (publicJwk != null) await keys.importPublicJwk(publicJwk);
};
</script>
<template>
  <div>
    <main class="min-h-dvh bg-background text-foreground">
      <div
        class="mx-auto flex w-full max-w-7xl flex-col gap-6 px-5 py-5 sm:px-6 lg:px-8"
      >
        <Header
          :publicKey="keys.publicKey.value"
          :privateKey="keys.privateKey.value"
        />
        <AlertStreamNotSupported v-if="!streamSupported.isSupported" />
        <section class="grid gap-6 lg:grid-cols-[0.3fr_0.9fr]">
          <KeyControlCard :keys="keys" />
          <div class="grid gap-6">
            <EncryptFileCard :files="enc" :keys="keys" />
            <DecryptFileCard :files="dec" :keys="keys" />
            <Algorithmns />
          </div>
        </section>
      </div>
    </main>
    <Toaster position="bottom-right" />
  </div>
</template>
